spring:
  application:
    name: ai-agent
  datasource:
    url: jdbc:postgresql://rm-cn-g4t49zdur00074go.rwlb.rds.aliyuncs.com:5432/ai-agent
    username: my_user
    password: zRT3LJNYGz@
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY:}
      chat:
        options:
          model: qwen-plus
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: ai.agent.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

